title: EduHub
email: itzme.eduhub.contact@gmail.com
description: >-
  EduHub is your partner in success, combining the power of technology with 
  reliable study resources to help you achieve your goals. Dive in and discover 
  the joy of learning with EduHub today!
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: itzfew

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
